[project]
name = "esphome-iot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "esphome>=2024.12.2",
    "setuptools>=75.6.0",
]
